server.port=8080

# Suas variaveis
CLIENT_ID=frontend-itau
CLIENT_SECRET=segredo123
JWT_SECRET=itau-secret-itau-secret-itau-secret

# Ativa endpoints do Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
