server.port=8080

# Variáveis da aplicação
CLIENT_ID=frontend-itau
CLIENT_SECRET=segredo123

# Ativa o endpoint de health para acesso externo
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# (Opcional) muda o path base dos endpoints de saúde
# management.endpoints.web.base-path=/actuator