name: Deploy Hom com Terraform

on:
  push:
    branches:
      - homolog
  pull_request:
    branches:
      - homolog
      
jobs:
  terraform:
    name: Terraform Apply (HOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        working-directory: terraform/hom
        run: terraform init

      - name: Validar código
        working-directory: terraform/hom
        run: terraform validate

      - name: Importar bucket existente no state (se necessário)
        working-directory: terraform/hom
        run: terraform import aws_s3_bucket.placeholder validador-hom-placeholder || true

      - name: Aplicar alterações na AWS
        working-directory: terraform/hom
        run: terraform apply -auto-approve

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
