name: Criar nova release automaticamente

on:
  push:
    branches:
      - develop

jobs:
  criar-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Obter o próximo número de release
        id: next_release
        run: |
          EXISTING=$(git ls-remote --heads origin "refs/heads/release/*" | awk -F'/' '{print $NF}' | sort -V)
          LAST=$(echo "$EXISTING" | tail -n1 | sed 's/release\///')
          if [[ -z "$LAST" ]]; then
            NEXT=1
          else
            NEXT=$((LAST + 1))
          fi
          echo "next_release=release/$NEXT" >> $GITHUB_OUTPUT

      - name: Criar e subir nova branch release
        run: |
          git fetch origin
          git checkout -b ${{ steps.next_release.outputs.next_release }}
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ steps.next_release.outputs.next_release }}

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
